### PR TITLE
Scrollbar bug fix for #68

### PR DESCRIPTION
**Pull request by alizahid**
Thanks for @bentinata for the suggest

### CODE REVIEW

**Comment by tsenart** [comment]
Can this have any unintended consequences or have you thought this through?

**Comment by alizahid** [comment]
I've tested this as best as I could, but it would be a good idea that you test once before releasing. I've mostly only refactored; no breaking changes.

**Comment by tsenart** [comment]
Released! It'll take a bit before it's propagated.

**Comment by alizahid** [comment]
Cool! Can you leave a comment when the extension is updated? I'm not familiar with the Chrome store process.

**Comment by tsenart** [comment]
Should be out now.

**Comment by alizahid** [comment]
Works perfectly!

**Pull request merged**
