### PR TITLE
Remove interference with renderable browser content types

### LINKED ISSUE #57: Incorrectly highlighting HTML files.
Sight is interfering with local HTML files. It switches the background color and text style instead of letting the browser decide. We need an option to filter file extensions.

This is with Sight enabled:
image

This is what it should do (Sight disabled):
image

### PR DESCRIPTION
**Pull request by tsenart**
Fixes #57 /cc @cjwelborn

### CODE REVIEW

**Comment by tsenart** [comment]
@cjwelborn: Would you please do some extra testing on your side with this change set? Once I have your +1, I'll merge and release this.

**Comment by cjwelborn** [comment]
Sure, as soon as I get home I'll check it out and report back.

**Comment by welbornprod** [comment]
`container` is empty sometimes, which causes the `cannot read property classList of null` error that I was running into before (why I added the conditional you asked about). When that happens the page is highlighted incorrectly with black text on a black background (What I thought was empty content, was actually just hidden by the colors), because of the default theme. Still happening because `contentType` is `null` and the `language` is either 'html' or 'xml'.

Changing from:
```javascript
if (!language) {
    return;
}
```

To:
```javascript
if (!language || (!contentType && ['html', 'xml'].indexOf(language) != -1)) {
  return;
}
```

...fixes the issue and highlights other files correctly.

**Comment by welbornprod** [comment]
I had a comment after the "i'll report back" comment that I deleted. If you saw it please ignore it. I checked the `fix-57` branch and everything seems okay. Files are highlighted correctly and html is ignored. (I can view my local html files just fine). Looks good to me.

**Comment by tsenart** [comment]
Released as 1.14.0

**Pull request merged**
