### PR TITLE
Add support for 'cc' extension for cpp files

### PR DESCRIPTION
**Pull request by vivekgalatage**

### CODE REVIEW

**Comment by tsenart** [comment]
Thank you!

**Comment by vivekgalatage** [comment]
Thanks for the quick merge. What is the frequency of publishing the changes to the web store?

**Comment by tsenart** [comment]
No regular frequency. I'll try to do it sometime soon.

**Comment by vivekgalatage** [comment]
Sure, thanks once again! :+1:

**Pull request merged**
